remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Optimizing GPT2 Inference with CUDA
description: A list of CUDA optimizations for various kernels in GPT2 inference stage.